### ISSUE TITLE
Create Weapons

### ISSUE THREAD

**Issue by Tthomas63** [Tthomas63/research_and_manufacturing#2]
Currently there is only 1 implemented weapon, the pistol. 

## Demo/Tutorial
It's implemented under `test_gamemode/entities/weapons/rm_pistol/` (Will probably be re-named to `ram_pistol`).

In here you'll find `shared.lua`, the shared code between the client and server.

Under `test_gamemode/entities/weapons/` you'll see several more that are not actual weapons, and some others. These are basically templates, they're `base_classes` without any actual implementation, just abstract classes ment to be inherited from and fully implemented.

- komerads_gun_base
- komerads_scoped_base
- komerads_shotty_base

These are copies of `Bob's SWEP Base` which he released free to use. I believe I've modified them slightly, and re-named them, but other than that I have no credit to these. For his instructions, step-by-step, here's a snip of text from the readme.txt:
```
Step 0: Renaming the base
	http://www.youtube.com/watch?v=lK9gNVqFTFw
	
Part 1: Model Hexing
	http://www.youtube.com/watch?v=BBH31PoHpUI

Part 2: Sounds
	http://www.youtube.com/watch?v=kpTqQD-Vqwo

Part 3: Irons and Variables
	http://www.youtube.com/watch?v=MhZWUDRN6Rw

Part 4: World Models with World Elements
	http://www.youtube.com/watch?v=SYupqRrUm-E

Part 5a: Spawn, hud, and kill icons
	https://www.youtube.com/watch?v=Z-Z6uNb7-w0

Part 5b: Spawn, hud, and kill icons continued
	https://www.youtube.com/watch?v=EcRXBfwdp-o
```

You probably won't need to go that in-depth. I believe copying one of the `empty <wep>` folders matching what weapon type you're making and re-naming it should be a good start.

For example, for making a shotgun copy the `empty shotgun` folder and re-name it `rm_shotgun` or `ram_shotgun` (We'll decide that later.)

Then open the `shared.lua` file and edit the weapon attributes inside. There should be vanilla models that can be used for now for model fields, such as CSS weapon models (If installed) or the default HL2 models. To easily get the model names, start a Gmod game in the sandbox gamemode, pull open the prop browser with `Q` and click the search box in the upper left. You can probably just search for either a viewmodel `v_` or a worldmodel `w_`.

EX:

`models/weapons/v_pist_usp.mdl`
`models/weapons/w_pist_usp.mdl`

Once done, you can start up Gmod and switch to the `test_gamemode`, then start a SinglePlayer game (I'll explain MP later). Open the console with `~`/` key.

If the console doesn't open, go-to options->keyboard->advanced and check `enable developer console`

Type:
```
sv_cheats 1
give <weapon_name>
```

Go back to the game and you should have your weapon. If not, see the console for Lua Errors. (Blue for Server, Orange/Yellow for Client I believe.) Should at least have a decent stack-trace with the line & col in the file.

# Weapons Wanted:
- [ ] Shotgun
- [ ] Magnum Pistol
- [ ] Crossbow
- [ ] Rocket Launcher
- [ ] Sniper
- [ ] Heavy Pistol
- [ ] SMG

Needs Further Explaining both technically and by what I mean:
- [ ] Grenades
- [ ] Teleport Guns(?)
- [ ] Gauss Gun
- [ ] Gluon Gun

**Comment by Tthomas63** [comment]
Ping

**Comment by ckcollab** [comment]
How do you change which items you start with? For easy testing

**Comment by Tthomas63** [comment]
There's the console command `give <weapon_class>` (works for other things too) or editing what you start with happens in `player_ram.lua` under the `LoadOut()` function
