### ISSUE TITLE
Flush out Research Menu

### ISSUE THREAD

**Issue by Tthomas63** [Tthomas63/research_and_manufacturing#3]
Finish Figuring Out Research Menu Categories and Items and what they do. Suggestions welcome:

Current Ideas:

### Armor
 - Tiers 1-5, all add 20% armor
#### Pistols
  - basic pistol (Shitty, high RoF)
  - magnum pistol (Strong, slow RoF)
  - heavy pistol (Strong, med RoF)
 #### SMGS
  - ? Not too Sure. Just 1 or 2
 #### Shotgun(s)
  - ? Not too Sure. Just 1 or 2
 #### Heavy(?)
  - Gauss Gun
  - Gluon Gun
  - Displacement Gun
  - LMG(?)
### Technology/Devices
 - Tripmines
 - Grenades
 - Satchels
 - EMP Grenades(?)
 - Drones(?)
 - Tiny Radios
 - Briefcase Turret?/Turret
 - ...
### Implants
 - Health Implants. (100->150)
 - Cybernetic Implant (Suit Zoom/Other func like highlighting visible players?)
 - Long Jump/Super Jump?
 - Muscle Implants (2+ tiers, better unarmed damage and faster running)
 - Self Destruct (For laughs, make it have a convar to even be enabled tho)

**Comment by ckcollab** [comment]
Should we just have many buttons for each thing, instead of many options we aren't supposed to click?

I.e....

![image](https://user-images.githubusercontent.com/2185159/42961958-44682ca8-8b45-11e8-9154-33d65db04cbc.png)

**Comment by ckcollab** [comment]
http://wiki.garrysmod.com/page/Derma_Basic_Guide

http://wiki.garrysmod.com/page/VGUI_Element_List

**Comment by ckcollab** [comment]
http://wiki.garrysmod.com/page/Category:DHTML

Can just use HTML actually, much easier!

**Comment by ckcollab** [comment]
Made this HTML: 
![image](https://user-images.githubusercontent.com/2185159/42983322-ef7e9b86-8b9a-11e8-9fb2-5f99bf9f78d2.png)

**Comment by ckcollab** [comment]
Can communicate Lua <-> JS this way: https://wiki.garrysmod.com/page/DHTML/AddFunction

```lua
-- Create the frame
local f = vgui.Create( "DFrame" )
f:SetSize( 800, 600 )
f:Center()

-- Create a green color variable
local color_green = Color( 0, 255, 0 )

-- Define the Javascript function in the DHTML element
local DHTML = vgui.Create( "DHTML", f )
DHTML:Dock( FILL )
DHTML:OpenURL( "http://wiki.garrysmod.com/page/VGUI/Elements/DHTML" )
DHTML:AddFunction( "console", "luaprint", function( str )
	MsgC( color_green, str ) -- Print the given string
end )

--This runs our function. Our function could also be called from Javascript on the DHTML's page.
DHTML:RunJavascript( "console.luaprint( 'Hello from Javascript!' );" )
```

**Comment by Tthomas63** [comment]
Damn, I never actually looked into the JS. That seems pretty powerful. Do you think we could load like semantic/riotjs stuff into the HTML like regularly as well? 

I think we could technically do every vgui in HTML.

**Comment by Tthomas63** [comment]
https://wiki.garrysmod.com/page/Object_Oriented_Lua

For re-factoring of the menu as an object possibly
