### ISSUE TITLE
Overhaul Research Menu to Use Voting System

### ISSUE THREAD

**Issue by Tthomas63** [Tthomas63/research_and_manufacturing#6]
Currently anybody on the team can immediately choose what research to do. We should change this to a voting style system instead, where the research with the most votes gets chosen.

If no-body votes one is chosen by randomly by the code.

**Comment by ckcollab** [comment]
Can you only do 1 research at once? How is research done? We could have an `update()` method of some kind, and each "tick" we can further research or not. Whichever research has the most votes on each team gets "ticked". After so-many-ticks the research is done. Like 1 "tick" should be a second, or something? 50 seconds to finish a research means for 50 ticks a majority of a team has to be on that research...?
